## YAML Template.
---
key: jaja
driverDB: com.mysql.cj.jdbc.Driver
urlDB: jdbc:mysql://sql8.freemysqlhosting.net:3306/sql8144411
userDB: sql8144411
passDB: ZEZRvssuFH
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
urlBase: http://localhost:8080/servidorLogin
